language: objective-c

install:
  - brew install neko haxe
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
  
before_script:
  - cd $TRAVIS_BUILD_DIR
  - haxelib dev integrate .
  - git clone https://github.com/thomasuster/haxe-websocket-server.git
  - haxelib dev haxe-websocket-server haxe-websocket-server
  - git clone https://github.com/MattTuttle/hxnet.git
  - haxelib dev hxnet hxnet
  - haxelib install munit
  - haxelib install hamcrest
  
script:
  - sh build.sh
  